window.CFG = {
  GAME_NAME: 'Rival Guys',
  VERSION: '1.31.0-self-host-ads-seo',
  MOBILE_OPT: (matchMedia('(pointer:coarse)').matches || /Android|iPhone|iPad|iPod/i.test(navigator.userAgent)),
  ROUND_TIME: 150,
  ROUND_SURVIVAL_RAMP: 60,
  MAX_ROUNDS: 5,
  WINS_TO_MATCH: 3,
  FIGHTER_COUNT: 8,
  MODES: [
    {id:'2v2', label:'2 VS 2', short:'2V2', teamSize:2, total:4, desc:'Fast duels. Every shove matters.', tag:'QUICK'},
    {id:'4v4', label:'4 VS 4', short:'4V4', teamSize:4, total:8, desc:'Balanced team brawl.', tag:'CLASSIC'},
    {id:'8v8', label:'8 VS 8', short:'8V8', teamSize:8, total:16, desc:'Maximum chaos on one arena.', tag:'MAYHEM'}
  ],
  TEAM_COLORS:{blue:0x2fa9ff,red:0xff405b},
  GRAVITY: 24,
  MOVE_SPEED: 6.2,
  ACCEL: 24,
  AIR_CONTROL: 0.48,
  JUMP_SPEED: 8.4,
  DASH_SPEED: 10.8,
  DASH_DURATION: 0.22,
  DASH_COOLDOWN: 2.4,
  PUNCH_RANGE: 2.62,
  PUNCH_FORCE: 7.2,
  PUNCH_LIFT: 2.25,
  PUNCH_COOLDOWN: 0.58,
  HIT_STUN_MIN: 0.55,
  HIT_STUN_MAX: 0.78,
  KNOCKDOWN_STUN_MIN: 1.05,
  KNOCKDOWN_STUN_MAX: 1.35,
  KNOCKDOWN_FORCE: 8.9,
  BODY_RADIUS: 0.56,
  STABILITY_BASE: 0.64,
  STABILITY_PER_HIT: 0.082,
  STABILITY_MAX: 1.08,
  STABILITY_DECAY: 0.19,
  FALL_Y: -13,
  ARENA_RADIUS: 14,
  BOT_RUBBER_LOSS: 0.82,
  BOT_RUBBER_WIN: 1.05,
  MAPS: [
    {id:'sky', name:'Sky Disc', unlock:1, desc:'Pure brawling on a shrinking floating disc.'},
    {id:'bridges', name:'Triple Bridges', unlock:2, desc:'Three risky bridges with breakable sections.'},
    {id:'towers', name:'Tumble Towers', unlock:3, desc:'Three stacked discs. Falling once is not the end.'},
    {id:'sweeper', name:'Spinning Sweeper', unlock:5, desc:'Jump the accelerating sweeper while fighting.'},
    {id:'crumble', name:'Crumbling Colosseum', unlock:7, desc:'Tiles sink two seconds after they are stepped on.'},
    {id:'wind', name:'Windy Peaks', unlock:10, desc:'Five islands and periodic outward wind gusts.'}
  ],
  SKINS: [
    {id:'pirate', name:'Captain', file:'assets/models/quaternius/pirate_captain.glb', type:'quaternius', icon:'🏴‍☠️', price:0, currency:'coins'},
    {id:'skeleton', name:'Bones', file:'assets/models/quaternius/skeleton.glb', type:'quaternius', icon:'💀', price:600, currency:'coins'},
    {id:'knight', name:'Knight', file:'assets/models/kaykit/Knight.glb', type:'kaykit', icon:'🛡️', price:850, currency:'coins'},
    {id:'rogue', name:'Rogue', file:'assets/models/kaykit/Rogue.glb', type:'kaykit', icon:'🗡️', price:1000, currency:'coins'},
    {id:'hooded', name:'Hooded Rogue', file:'assets/models/kaykit/Rogue_Hooded.glb', type:'kaykit', icon:'🥷', price:60, currency:'gems'},
    {id:'barbarian', name:'Barbarian', file:'assets/models/kaykit/Barbarian.glb', type:'kaykit', icon:'🪓', price:1400, currency:'coins'},
    {id:'mage', name:'Mage', file:'assets/models/kaykit/Mage.glb', type:'kaykit', icon:'🪄', price:90, currency:'gems'},
    {id:'ranger', name:'Ranger', file:'assets/models/kaykit/Ranger.glb', type:'kaykit', icon:'🏹', price:1750, currency:'coins'}
  ],
  EMOTES: [
    {id:'wave', name:'Hello!', icon:'👋', action:'emoteWave', price:0, currency:'coins', rarity:'COMMON'},
    {id:'cheer', name:'Big Cheer', icon:'🎉', action:'emoteCheer', price:0, currency:'coins', rarity:'COMMON'},
    {id:'pushups', name:'Push-Ups', icon:'💪', action:'emotePushups', price:220, currency:'coins', rarity:'COMMON'},
    {id:'sit', name:'Chill Sit', icon:'😎', action:'emoteSit', price:300, currency:'coins', rarity:'RARE'},
    {id:'throw', name:'Air Toss', icon:'🤾', action:'emoteThrow', price:350, currency:'coins', rarity:'RARE'},
    {id:'pickup', name:'Show-Off', icon:'✨', action:'emotePickup', price:420, currency:'coins', rarity:'RARE'},
    {id:'interact', name:'Hype Up', icon:'🙌', action:'emoteInteract', price:480, currency:'coins', rarity:'RARE'},
    {id:'sneak', name:'Sneaky', icon:'🕵️', action:'emoteSneak', price:520, currency:'coins', rarity:'EPIC'},
    {id:'shuffleL', name:'Side Shuffle', icon:'🕺', action:'emoteDodgeLeft', price:14, currency:'gems', rarity:'EPIC'},
    {id:'shuffleR', name:'Quick Step', icon:'💃', action:'emoteDodgeRight', price:14, currency:'gems', rarity:'EPIC'},
    {id:'crouch', name:'Low Pose', icon:'😏', action:'emoteCrouch', price:620, currency:'coins', rarity:'EPIC'},
    {id:'crawl', name:'Floor Move', icon:'😂', action:'emoteCrawl', price:18, currency:'gems', rarity:'LEGENDARY'}
  ],
  PERSONALITIES: ['Bully','Camper','Trickster','Rookie']
};

window.Util = {
  clamp(v,a,b){ return Math.max(a,Math.min(b,v)); },
  lerp(a,b,t){ return a+(b-a)*t; },
  rand(a,b){ return a+Math.random()*(b-a); },
  pick(arr){ return arr[(Math.random()*arr.length)|0]; },
  shuffle(arr){ for(let i=arr.length-1;i>0;i--){ const j=(Math.random()*(i+1))|0; [arr[i],arr[j]]=[arr[j],arr[i]]; } return arr; },
  formatTime(sec){ sec=Math.max(0,Math.ceil(sec)); return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`; },
  dist2D(a,b){ const dx=a.x-b.x,dz=a.z-b.z; return Math.hypot(dx,dz); },
  angleDelta(a,b){ let d=(b-a+Math.PI)%(Math.PI*2)-Math.PI; return d; }
};
